/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.adh39.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;

/**
 * This class initialize the Game App.
 * It generates two players.
 */
public class App {
  final TextPlayer p1;
  final TextPlayer p2;

  /**
   * Constructs a Game app which consists of two players.
   * @param theBoard1/theBoard2 is the board for two players to act on, inputSource/out is the place to read/write input from/to. 
   */
  public App(Board<Character> theBoard1, Board<Character> theBoard2, BufferedReader inputSource, PrintStream out) {
    this.p1 = new TextPlayer("Player1", theBoard1, inputSource, out, new V1ShipFactory());
    this.p2 = new TextPlayer("Player2", theBoard2, inputSource, out, new V1ShipFactory());
  }

  /**
   * This method execute one placement phase where one ship is put on the board of each player.
   * @throws IOException if the doOnePlacement throws a IOException.
   */
  public void doPlacementPhase() throws IOException{
    for (String str : p1.shipsToPlace) {
      p1.doOnePlacement(str);
    }
    for (String str : p2.shipsToPlace) {
      p2.doOnePlacement(str);
    }
  }

  /**
   * This function runs the main program setting up two players and have each player place one ship on their board.
   */
  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    App app = new App(b1, b2, new BufferedReader(new InputStreamReader(System.in)), System.out);
    app.doPlacementPhase();
  }
}











